# Site settings
title: "Valaistuneet.fi"
author: "Artanicus"
email: help@valaistuneet.fi
description: "Suomen Virallinen ENL-yhteisö"
baseurl: ""
url: "http://www.valaistuneet.fi"
source-url: "https://github.com/artanicus/artanicus.github.io/"
#permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'buildpublish.sh']

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman